version: '3.1'

services:
  db:
    image: mysql
    restart: always
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: udsdozEyKNBR
      MYSQL_DATABASE: avreg6_db
      MYSQL_USER: avreg
      MYSQL_PASSWORD: udsdozEyKNBR
    networks: 
        - avreg_bridge

  
  avreg:
    image: dzirtt:avreg
    networks: 
        - avreg_bridge
    ports:
        - "80:80"
    depends_on:
        - db
    environment:
        MYSQL_DATABASE: avreg6_db
        MYSQL_USER: avreg
        MYSQL_PASSWORD: udsdozEyKNBR
    links:
      - "db:database"

networks:
  avreg_bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.11.0/29

